### ISSUE TITLE
LUMO NIRS System-ask a question for the prefrontal configuration with 12 arrays 

### ISSUE THREAD

**Issue by Qing1996-creator** [DOT-HUB/DOT-HUB_toolbox#18]
Dear Dr. Rob Cooper,
Hello!
Could I ask you some questions? When I use the LUMO NIRS system with 12 array to analyze the acquired prefrontal signals, the DOT-HUB_toolbox always shows the following issues:
1) Incorrect use of 'zeros';
2) error: DOTHUB_reconstruction (line 169)
              hbo.vol = zeros(nFrames,nNodeVol,nCond);
3) error:   PipelinePL (line 62)
[dotimg, dotimgFileName] = DOTHUB_reconstruction(preproFileName[],invjacFileName,rmapFileName,'saveVolumeImages',true);

I have tried to process it many times, but I still can't solve them.  Thus, could you help me to address them?
Looking forward to your reply.

Best regards.

**Comment by RJCooperUCL** [comment]
Hi - apologies I am only just seeing this. If you still have problems feel free to email me to ask for help or direct me to github comments. robert.cooper@ucl.ac.uk
