### ISSUE TITLE
Bug in the Homer2 pre-processing stage

### ISSUE THREAD

**Issue by nidadu** [DOT-HUB/DOT-HUB_toolbox#19]
I found a bug after the recent commit when running the section of Homer2 pre-processing in the PipelineExample1.m. In my data processing I have used the code line `[prepro, preproFileName] = DOTHUB_runHomerPrepro(nirsFileName,cfgFileName);` rather than running it line by line. The received error message is attached:

![image](https://user-images.githubusercontent.com/64904429/146795008-d4ec9769-77eb-481d-bf95-3eb7021054ef.png)

I seems that after the recent changes the variable `SD3D` is not correctly declared. Could someone have a look at this? I don't feel too confident with this toolbox to comfortably suggest a fix.

**Comment by RJCooperUCL** [comment]
Fixed.
